### ISSUE TITLE
Houston, we have a problem

### ISSUE THREAD

**Issue by alexchetv** [matreshkajs/matreshka.io#3] opened 2016-02-14 14:47 UTC
userAgent:  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Error: Cannot read property 'length' of null

**Comment by finom** [comment] 2016-02-15 15:14
Hmm, cannot reproduce. Are you still getting the same issue?

**Comment by finom** [comment] 2016-03-08 18:11
Cannot reproduce, closing.

**Closed by finom** 2016-03-08 18:11 UTC
